### ISSUE TITLE
Chromebook with Linux OS parsed as Android

### ISSUE THREAD

**Issue by darrenklein** [beam-community/ua_parser#24]
Hi again!  I was testing parsing some different user agent strings, and I tried out a string for a Chromebook running Linux -

```
iex(1)> str = "Mozilla/5.0 (Linux; Android 7.1.1; Acer Chromebook R13 (CB5-312T) Build/R66-10452.85.0; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/56.0.2924.87 Safari/537.36"
iex(2)> str |> UAParser.parse()

%UAParser.UA{
  device: %UAParser.Device{
    brand: "Acer",
    family: "Acer Chromebook R13 (CB5-312T)",
    model: "Chromebook R13 (CB5-312T)"
  },
  family: "Chrome Mobile WebView",
  os: %UAParser.OperatingSystem{
    family: "Android",
    version: %UAParser.Version{
      major: "7",
      minor: "1",
      patch: "1",
      patch_minor: nil
    }
  },
  version: %UAParser.Version{
    major: "56",
    minor: "0",
    patch: "2924",
    patch_minor: "87"
  }
}
```

Among other things, I expected that the `os.family` would be `"Linux"`, rather than `"Android"`.

Unfortunately, I don't own a Chromebook with Linux, so I can only go by the sample user agent strings I found at http://www.webapps-online.com/online-tools/user-agent-strings/dv/brand642387/chromebook

What do y'all think about this?  If you feel it's a legit issue, I'd be happy to pick it up and open a PR for it.  Again, I can't verify the accuracy of the UA string, and this was the only example that I could find, so if you feel the source isn't reliable enough to warrant making any changes, I'd certainly understand.

Thanks for all of your hard work!

**Comment by doomspork** [comment]
Hi @darrenklein thank you for the report! The user agent patterns come from https://github.com/ua-parser/uap-core. It's possible that their patterns need to be updated or that we need to update our pattern file.

Would you be willing to investigate?

**Comment by darrenklein** [comment]
@doomspork Sure thing, I'll take a look into this.  Among other things, I'll see if I can find examples of a Linux Chromebook from some other sources, make sure that's a valid example.

**Comment by Hanspagh** [comment]
@darrenklein maybe you you could also open the issue at https://github.com/ua-parser/uap-core

**Comment by darrenklein** [comment]
@Hanspagh thanks for reminding me about this!  I've been quite busy and forgot all about it.  Actually, I'd appreciate your thoughts on this - I don't have access to a Linux Chromebook, so I'm not able to verify the example string from the source I provided... given that, do you think that warrants posting an issue on uap-core?  I'm reconsidering whether it was appropriate for me to open this issue at all, given then limited information I had.

**Comment by Hanspagh** [comment]
@darrenklein Good question, since I don't think its an issue with this `ua_parser` I would like to close this issue and my thinking was that if this is actually an issue we should open it where it problem is. If it was me I would bring this up in https://github.com/ua-parser/uap-core, maybe not as an issue, but more as a quisiton.

**Comment by darrenklein** [comment]
@Hanspagh Thanks very much for your hard work and your thoughts on this.
