### ISSUE TITLE
Webview within iPadOS parsed as Apple Mail

### ISSUE THREAD

**Issue by ytnobody** [beam-community/ua_parser#31]
Yesterday I encountered a behavior like as a title. 

Situation: When sent a https request from my iPad app to my phoenix app that using ua_parser

UserAgent string is `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko)`

```
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko)" |> UAParser.parse()
%UAParser.UA{
  device: %UAParser.Device{brand: nil, family: nil, model: nil},
  family: "Apple Mail",
  os: %UAParser.OperatingSystem{
    family: "Mac OS X",
    version: %UAParser.Version{
      major: "10",
      minor: "15",
      patch: nil,
      patch_minor: nil
    }
  },
  version: %UAParser.Version{
    major: "605",
    minor: "1",
    patch: "15",
    patch_minor: nil
  }
}
```

**Comment by doomspork** [comment]
Hello @ytnobody and thank you for the report! Incorrect UA bugs should be directed to https://github.com/ua-parser/uap-core. That's the repo from which we pull the comprehensive UA patterns from.

Let me know if you have any questions :grin:
