### ISSUE TITLE
hex.pm version is outdated

### ISSUE THREAD

**Issue by isubasti** [beam-community/ua_parser#97]
There seems to be version 1.9.0 and 1.9.1 on hex.pm but it's from 2021 while 1.9.0 and 1.9.1 on github release is from earlier this year. will these version be published to hex as well?

**Comment by doomspork** [comment]
@isubasti I will investigate but have you confirmed the 1.9.1 in Hex _isn't_ the 1.9.1 here? If we review the git history there was never a 1.9.1 in 2021. This _feels_ like a hex bug or a configuration issue 🤔

**Comment by isubasti** [comment]
> @isubasti I will investigate but have you confirmed the 1.9.1 in Hex _isn't_ the 1.9.1 here? If we review the git history there was never a 1.9.1 in 2021. This _feels_ like a hex bug or a configuration issue 🤔 

https://github.com/beam-community/ua_parser/commit/49305de88eb2b6b47a6c8592f767bc957d4ffb23 it's this commit I think that's released in hex as 1.9.1
